#!/bin/sh

# install PyXML-0.8.4 (missing from pip)
cd /tmp
wget http://biocluster.ucr.edu/~tbackman/vagrantImages/PyXML-0.8.4.tar.gz
tar xvfz PyXML-0.8.4.tar.gz
cd PyXML-0.8.4
# There is a bug in newer Ubuntu systems that prevents this from building
# Solution: echo '#define HAVE_MEMMOVE 1' >> /usr/include/python2.7/pyconfig.h
python setup.py build
sudo python setup.py install
cd ..
rm -rf PyXML-0.8.4.tar.gz PyXML-0.8.4
