#!/bin/sh
# manually install packages in /usr/local/lib/python2.7/dist-packages:
cd /tmp
wget http://biocluster.ucr.edu/~tbackman/vagrantImages/django_cron.tgz
wget http://biocluster.ucr.edu/~tbackman/vagrantImages/django_guest.tgz
wget http://biocluster.ucr.edu/~tbackman/vagrantImages/gyroid_utils.tgz
tar xvfz django_cron.tgz
tar xvfz django_guest.tgz
tar xvfz gyroid_utils.tgz
mv guest /usr/local/lib/python2.7/dist-packages/
mv django_cron /usr/local/lib/python2.7/dist-packages/
mv gyroid_utils /usr/local/lib/python2.7/dist-packages/
rm -rf guest django_cron django_cron.tgz django_guest.tgz gyroid_utils.tgz gyroid_utils

